config/routes.rb
# -*- encoding : utf-8 -*-
Blog::Application.routes.draw do
  root to: 'articles#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get "about" => "users#about"

  resources :articles
  get "/articles/tagging/:tag", to: "articles#tagging", as: :tagging
end

app/models/article.rb
# -*- encoding : utf-8 -*-
class Article < ActiveRecord::Base
  # :dependent used to destroy taggings when article was destroyed
  has_many :taggings, dependent: :destroy

  # :after_remove used to update article and tag when tag_list was edited
  has_many :tags, through: :taggings, after_remove: proc { |article, tag| article.touch; tag.touch  }
  
  validates :title, :content, :presence => true
  validates :title, uniqueness: true
  validates :content, length: { minimum: 20 }

  self.per_page = 10

  scope :published, -> { joins(:tags).where("tags.name != ?", "draft").uniq }

  def tag_list=(value)
    tags = value.split(',').map { |tag| tag.strip.downcase }.reject { |t| t.blank? }

    self.tags = if tags.include?('draft')
                  [Tag.find_or_create_by(name: 'draft')]
                else
                  tags.map{ |tag| Tag.find_or_create_by(name: tag) }
                end
  end

  def tag_list
    self.tags.map(&:name).join(', ')
  end

  def draft?
    tags.where(name: 'draft').any?
  end
end

app/models/tag.rb
# -*- encoding : utf-8 -*-
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings

  scope :ordered, -> { order('name') }

  def to_param
    name
  end

  def draft?
    name == 'draft'
  end
end

app/models/tagging.rb
# encoding: UTF-8
class Tagging < ActiveRecord::Base
  # :touch used to update article when new tag was added
  belongs_to :article, touch: true

  # :touch used to update tag when tagging was destroyed
  belongs_to :tag, counter_cache: :articles_count, touch: true
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User
  attr_accessor :email

  def initialize(email)
    @email = email
  end

  def admin?
    email == APP_CONFIG['admin_email']
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= session[:email] ? User.new(session[:email]) : nil
  end

  def logged_in?
    !!current_user
  end

  private

  def require_admin
    redirect_to root_path if !current_user.try(:admin?)
  end
end

app/controllers/articles_controller.rb
# -*- encoding : utf-8 -*-
class ArticlesController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = current_user && current_user.admin? ?
      Article.order("articles.id DESC").paginate(page: params[:page]) :
      Article.published.order("articles.id DESC").paginate(page: params[:page])

    @page_title = '首页'
  end

  def new
    @article = Article.new
    @page_title = '发布文章'

    render layout: "wide"
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def show
    raise ActiveRecord::RecordNotFound if !current_user.try(:admin?) && @article.draft?
    @page_title = "#{@article.title}"
    @page_description = @article.title
  end

  def edit
    @page_title = "#{@article.title}"

    render layout: "wide"
  end

  def update
    if @article.update_attributes(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find params[:id]
    @article.destroy

    redirect_to articles_path
  end

  def tagging
    tag = Tag.find_by_name! params[:tag]
    raise ActiveRecord::RecordNotFound if tag.draft? && !current_user.try(:admin?)

    @articles = tag.articles.order('id DESC').paginate(page: params[:page])
    @page_title = "#{tag.name} 相关文章"
    render :index
  end

  private
    def find_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :tag_list)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    email = auth_hash[:info][:email]

    if email == 'reyes.yang@gmail.com'
      session[:email] = email
      cookies[:admin] = true
    end

    redirect_to root_path
  end

  def destroy
    session[:email] = nil
    cookies.delete :admin

    redirect_to root_path, notice: '成功退出'
  end

  private
    def auth_hash
      request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  def about
    @page_title = '关于'
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
  def format_text(text, options = {})
    sanitize markdown(text)
  end

  def markdown(text)
    markdown_render = Redcarpet::Render::HTML.new no_style: true, hard_wrap: true
    markdown = Redcarpet::Markdown.new(markdown_render,
                                       autolink: true,
                                       no_intra_emphasis: true,
                                       fenced_code_blocks: true,
                                       strikethrough: true,
                                       superscript: true)
    markdown.render(text.to_s)
  end
  
  def join_tags(article)
    article.tags.map { |tag| "<a href='/articles/tag/#{tag.id}'>#{tag.name}</a>" }.join("; ")
  end

  def cache_key_for_tags
    last_updated_at = Tag.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "tags-#{last_updated_at}-v1"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_article.html.haml
- cache article do
  %article.article
    %header.clearfix
      %h3.article_title
        = link_to article.title, article_url(article)
      %span.created_at<
        = t 'post_at'
        = article.created_at.in_time_zone(+8.hours).strftime('%D %T')
      - if article.tags.any?
        .tags
          %span= t 'tags'
          %ul.unstyled
            = render partial: 'tags/tag', collection: article.tags
      %span.operation.admin
        = link_to t('edit'), edit_article_path(article)
        = link_to t('destroy'), article, data: { confirm: 'Are you sure?' }, :method => :delete

app/views/articles/_article_header.html.haml
- cache [article, :header] do
  %header.clearfix
    %h3.article_title
      = link_to article.title, article_path(article)
    %span.created_at<
      = t 'post_at'
      = time_tag article.created_at.to_date
    - if article.tags.any?
      .tags
        %span= t 'tags'
        %ul.unstyled
          = render partial: 'tags/tag', collection: article.tags
    %span.operation.admin
      = link_to t('edit'), edit_article_path(article)
      = link_to t('destroy'), article, data: { confirm: 'Are you sure?' }, :method => :delete

app/views/articles/_article_summary.html.haml
- cache [article, :summary] do
  %article.article
    = render partial: 'article_header', object: article, as: :article

app/views/articles/_form.html.haml
= form_for @article do |f|
  #edit-area
    .field= f.text_field :title
    .field= f.text_field :tag_list
    .field
      #wmd-button-bar
      = f.text_area :content, :id => 'wmd', rows: 13
    .actions= f.submit t('post_article'), :class => 'btn'
  #preview-area
    #wmd-preview

app/views/articles/edit.html.haml
%header.red_header
  %h2= t 'edit_article'
= render 'form'

app/views/articles/index.html.haml
-%w(success error info).each do |type|
  -if flash[type.to_sym]
    %div{class: "alert alert-#{ type }"}
      %a{class: "close", "data-dismiss" => "alert", href: "#"}×
      = raw flash[type.to_sym]

-if logged_in? && current_user.admin?
  .top_operation= link_to t('new_article'), new_article_path

- if @articles
  = render partial: 'article_summary', collection: @articles, as: :article
  = will_paginate @articles

app/views/articles/new.html.haml
%header.red_header
  %h2= t 'create_article'
= render 'form'

app/views/articles/show.html.haml
= render @article
= render :partial => 'layouts/disque'

app/views/layouts/_aside.html.haml
%aside#global-aside
  %header
    = link_to 'Reyes Yang', '/', :id => 'logo'
    %h3#me
      = link_to '吾', '/about'
      #passage
        - if logged_in?
          = link_to '/logout', id: 'logout-button', class: 'dark', method: :delete, data: { confirm: '确认退出吗？' } do
            %span 退出
        - else
          = link_to '/auth/github', id: 'login-button', class: 'dark' do
            %span 登录

  %section#aside_tags
    - cache cache_key_for_tags do
      %ul.unstyled
        = render partial: 'tags/tag', collection: Tag.order(:name)

app/views/layouts/_disque.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//reyesyang.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/layouts/_footer.html.haml
%footer#global_footer
  #cc
    = t 'licence_prefix'
    = link_to '//creativecommons.org/licenses/by/4.0/', :rel => 'license', :target => '_blank' do
      = image_tag '//i.creativecommons.org/l/by/4.0/80x15.png', :alt => '知识共享许可协议', :id => 'cc_icon'
      %strong= t 'licence'
    = t 'licence_suffix'
  #copy<
    &copy; #{DateTime.now.year} &hearts; &nbsp;
    = link_to t('copy_right'), '/about'

app/views/layouts/_google_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '#{APP_CONFIG['ga_account']}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{charset: 'utf-8'}
    %title= "#{APP_CONFIG['default_title']}#{' | ' + @page_title if @page_title}"
    %meta{name: 'description', content: "#{@page_description || APP_CONFIG['default_description']}"}
    %meta{:'http-equiv' => 'X-UA-Compativle', content: 'IE=Edge'}
    = csrf_meta_tag
    = stylesheet_link_tag 'application', data: { :'turbolinks-track' => true }
    = javascript_include_tag 'application', data: { :'turbolinks-track' => true }
    = yield :head
    /[if lt IE 9]
      %script{:src => "//html5shim.googlecode.com/svn/trunk/html5.js"}
    = render :partial => 'layouts/google_analytics'

  %body{id: "#{controller_name}-#{action_name}"}
    %section#main-wrapper
      = render :partial => 'layouts/aside'
      %section#main-content= yield
      .clearfix
    = render :partial => 'layouts/footer'
    = yield :js

app/views/layouts/wide.html.haml
!!! 5
%html
  %head
    %title= "#{@page_title + ' - ' if @page_title}" + APP_CONFIG['default_title']
    %meta{:charset => 'utf-8'}
    %meta{:name => 'description', :content => "#{@page_description || APP_CONFIG['default_description']}"}
    = csrf_meta_tag
    = stylesheet_link_tag 'application', data: { :'turbolinks-track' => true }
    = javascript_include_tag 'application', data: { :'turbolinks-track' => true }
    = yield :head
    /[if lt IE 9]
      %script{:src => "//html5shim.googlecode.com/svn/trunk/html5.js"}
    = render :partial => 'layouts/google_analytics'

  %body{ id: "#{controller_name}-#{action_name}" }
    %section#wide-main-wrapper
      = yield
      .clearfix
    = render :partial => 'layouts/footer'
    = yield :js

app/views/tags/_tag.html.haml
- if tag.articles_count > 0
  - cache tag do
    %li{class: tag.draft? ? "tag admin" : "tag"}
      = link_to tagging_path(tag), :class=>'aside_tag' do
        %span{class: 'label'}= tag.name
      %span.count
        &times; #{tag.articles_count}

app/views/users/about.html.haml
%header
  %h2= t 'about_me'

.self_introduction= sanitize t('temp_me')

= render :partial => 'layouts/disque'